name: VM_BE_deploy
on: 
  workflow_dispatch:

jobs:
  build-and-push: 
    name: Push to VM and deploy
    runs-on: ubuntu-latest 
    steps:
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        port: ${{ secrets.VM_PORT }}
        script: |
          whoami
          ls
          git pull origin main
          sudo apt install -y nodejs
          sudo apt install -y npm
          npm install
          npm run build
          npm install pm2 -g
          pm2 restart backend
        

