name: Deploy

on:
  workflow_dispatch

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy code
        env:
          PASSWORD: ${{ secrets.VM_PASSWORD }}
          HOSTNAME: ${{ secrets.VM_HOST }}
          USER_NAME: ${{ secrets.VM_USER }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
            cd PSA_BE &&
            git pull origin main &&
            sudo npm install &&
            sudo npm run build &&
            sudo pm2 restart backend
          '

